apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv-2
  labels:
    type: local
    app: stackoverflow
spec:
  storageClassName: manual
  claimRef:
    name: database-pvc-2
    namespace: laravel

  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc-2
  namespace: laravel
  labels:
    app: stackoverflow
spec:
  storageClassName: manual
  volumeName: database-pv-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
