apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: laravel
  labels:
    app: stackoverflow
spec:
  type: ClusterIP
  selector:
    app: stackoverflow
  ports:
    - protocol: TCP
      name: database-port
      port: 5432
      targetPort: database