apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv-1
  labels:
    type: local
    app: stackoverflow
spec:
  storageClassName: manual
  claimRef:
    name: database-pvc-1
    namespace: django

  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc-1
  namespace: django
  labels:
    app: stackoverflow
spec:
  storageClassName: manual
  volumeName: database-pv-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
